name: pw tests with allure

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  e2eTests:
    #timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install dependencies
        run: npm install
      - name: install pw
        run: npx playwright install --with-deps
      - name: run pw
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results
          retention-days: 20
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Allure Report
        run: npx allure generate allure-results -o allure-report
      - name: Generate Allure Report
        run: npx allure generate allure-results -o allure-report
      - name: deploy allure report to gh pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
